/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Clases.*;
import java.io.BufferedReader;
import java.io.*;
import java.io.InputStreamReader;
import java.util.Calendar;
import javax.swing.*;

/****  @author Ing. Miguel Angel Silva Zapata  *****/
public class Backupfrm extends javax.swing.JInternalFrame {
   Controlador control=new Controlador();
   
    
    public Backupfrm() {
     initComponents();
     this.setFrameIcon(new ImageIcon(this.getClass().getResource("/Imagenes/icoChiqui.png")));
    }
    
    /*public void CrearBackupBD(String us,String ps,String bd){
        Calendar c=Calendar.getInstance();
        String fecha=String.valueOf(c.get(Calendar.DATE));
        fecha=fecha+"_"+ String.valueOf(c.get(Calendar.MONTH));
        fecha=fecha+"_"+ String.valueOf(c.get(Calendar.YEAR));
        fecha=fecha+"_"+ String.valueOf(c.get(Calendar.HOUR_OF_DAY));
        fecha=fecha+"_"+ String.valueOf(c.get(Calendar.MINUTE));
        fecha=fecha+"_"+ String.valueOf(c.get(Calendar.SECOND));
        
        //String fecha=control.Fecha()+control.Hora();
        Runtime rutime=Runtime.getRuntime();
        File backup=new File("D:/Respaldos/backup");
        backup.mkdirs();
        File backupFile=new File("D:/Respaldos/backup/backup"+"_"+fecha+".sql");
        try{
         InputStreamReader irs;
         BufferedReader br;
         FileWriter filewrite=new FileWriter(backupFile);
         String patch="C:\\xampp\\mysql\\bin\\";
         Process chil=rutime.exec(patch+"mysqldump"+" --opt "+" --user="+us+" --password="+ps+" --databases "
         +bd+" -R");
         irs=new InputStreamReader(chil.getInputStream());
         br=new BufferedReader(irs);         
         String line;
         while((line=br.readLine())!=null){
          filewrite.write(line+"\n");
         }
         JOptionPane.showMessageDialog(null, "Copia de Seguridad Exitosa");         
        }
        catch(Exception e){
         System.out.println("Errores");
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backupear = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backupear.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        Backupear.setText("Backup BD");
        Backupear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackupearActionPerformed(evt);
            }
        });
        getContentPane().add(Backupear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackupearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackupearActionPerformed
        //control.CrearBackupBD("root","", "comercialrc");
        JOptionPane.showMessageDialog(null, InfoGeneral.rutades);
            
                
        
    }//GEN-LAST:event_BackupearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backupear;
    // End of variables declaration//GEN-END:variables
}
