/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

/**
 *
 * @author User
 */
import Clases.*;
import com.toedter.calendar.JDateChooser;
import java.beans.PropertyChangeEvent;
import java.lang.reflect.Field;
import java.util.Date;
public class DeudasenGeneral extends javax.swing.JInternalFrame {
    Controlador control=new Controlador();Mimodelo modelo=new Mimodelo();
    /**
     * Creates new form DeudasenGeneral
     */
    public DeudasenGeneral() {
      initComponents();setTitle("Lista General de Deudas");tDeudores.setModel(modelo);PonerFechaActual();
      modelo.setColumnIdentifiers(new String[]{"ID","F_Deuda","Cliente","Dirección","Fono","Comprobante","Deuda","F_Pago","DiasqueFaltan","DiasdeRestraso"});
      control.hideTableColumn(tDeudores, 0);control.setWidthTableColumn(tDeudores,210,2,3);control.setWidthTableColumn(tDeudores,140,5);
      MostrarDeudores();
      
      //****************************CONTROLAR EL CAMBIO DE FECHA***********************************
     f_Desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      @Override
      public void propertyChange(PropertyChangeEvent evt) {
       if("date".equals(evt.getPropertyName())){ JDateChooser isse=(JDateChooser)evt.getSource(); boolean isdatasele=false;
        try { Field dateselfi=JDateChooser.class.getDeclaredField("dateSelect"); dateselfi.setAccessible(true); isdatasele=dateselfi.getBoolean(isse);
        } 
        catch (Exception e) {
         control.Sql="select datediff('"+control.Formato_Amd(F_Hasta.getDate())+"','"+control.Formato_Amd(f_Desde.getDate())+"')";
         if(Integer.parseInt(control.DevolverRegistroDto(control.Sql, 1))<0){ 
             //MostrarDeudores();
         }  
         else   MostrarDeudores();
        }
       }
      }
     });
     
     F_Hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      @Override
      public void propertyChange(PropertyChangeEvent evt) {
       if("date".equals(evt.getPropertyName())){  JDateChooser isse=(JDateChooser)evt.getSource();
        boolean isdatasele=false;
        try {
         Field dateselfi=JDateChooser.class.getDeclaredField("dateSelect");
         dateselfi.setAccessible(true);isdatasele=dateselfi.getBoolean(isse);
        } 
        catch (Exception e) {
         control.Sql="select datediff('"+control.Formato_Amd(F_Hasta.getDate())+"','"+control.Formato_Amd(f_Desde.getDate())+"')";
         if(Integer.parseInt(control.DevolverRegistroDto(control.Sql, 1))<0){ 
          //MostrarDeudores1();
         }   
         else
          MostrarDeudores();
        }
       }
      }
     });
    }
    
   public  void MostrarDeudores(){
    control.Sql="select de.idDeuda,date_format(v.fecvta,'%d-%m-%Y') F_Deuda,cl.nomclie Cliente,cl.dir Dirección,cl.Fono,concat(tc.tipcompr,': ',"
    + "cb.serie,'-',cb.nume) Comprobante,de.montdeu Deuda,date_format(de.fecdeud,'%d-%m-%Y') F_pago,if(datediff(de.fecdeud,curdate())<0,0,"
    + "datediff(de.fecdeud,curdate())) DiasqueFaltan,if(datediff(curdate(),de.fecdeud)<=0,0,datediff(curdate(),de.fecdeud)) DiasdeRetraso" 
    +" from deuda de inner join venta v on v.idventa=de.idventa inner join cliente cl on cl.idcliente=v.idcliente inner join compventa cv on cv.idventa"
    + "=v.idventa inner join comprobantes cb on cb.idcomprobantes=cv.idcomprobantes inner join tipocomprobante tc on tc.idtipocomprobante="
    + "cb.idtipocomprobante where de.montdeu>0 and (cl.nomclie like'%"+txtBuscar.getText()+"%' or tc.tipcompr like'%"+txtBuscar.getText()+"%' "
     +" or cb.nume like'%"+txtBuscar.getText()+"%')  and (v.fecvta between '"+control.Formato_Amd(f_Desde.getDate())+"' and '"
     +control.Formato_Amd(F_Hasta.getDate())+"')"; control.LlenarJTabla(modelo, control.Sql, 10);    
   }
    public void PonerFechaActual(){
     f_Desde.setDate( new Date());F_Hasta.setDate( new Date());   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bSalir = new javax.swing.JButton();
        bImprimir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        f_Desde = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        F_Hasta = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDeudores = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSalir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bSalir.setForeground(new java.awt.Color(0, 51, 102));
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        bSalir.setMnemonic('s');
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel2.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 7, 114, 45));

        bImprimir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bImprimir.setForeground(new java.awt.Color(0, 51, 102));
        bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print.png"))); // NOI18N
        bImprimir.setMnemonic('i');
        bImprimir.setText("Imprimir");
        bImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(bImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 7, 114, 45));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Desde");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, -1, -1));

        f_Desde.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(f_Desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 19, 130, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Hasta");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        F_Hasta.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(F_Hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tDeudores.setForeground(new java.awt.Color(0, 51, 102));
        tDeudores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tDeudores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDeudoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDeudores);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, 1170, 470));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 13, 1115, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Buscar");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1190, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImprimirActionPerformed
     
    }//GEN-LAST:event_bImprimirActionPerformed

    private void tDeudoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDeudoresMouseClicked
     
    }//GEN-LAST:event_tDeudoresMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
      MostrarDeudores();
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser F_Hasta;
    private javax.swing.JButton bImprimir;
    private javax.swing.JButton bSalir;
    private com.toedter.calendar.JDateChooser f_Desde;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tDeudores;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
