/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.*;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Omr
 */
public class FrmGenerarGuiaRemision extends javax.swing.JDialog implements ActionListener {

    private Controlador control = new Controlador();
    private Mimodelo model = new Mimodelo();
    private String idComprobanteGenerado = null;
    private String motivoTraslado = "";
    private String idVenta = null;
    private String idGuiaRemision = null;

    /**
     * Creates new form FrmGenerarGuiaRemision
     */
    public FrmGenerarGuiaRemision(java.awt.Frame parent, boolean modal) {
     super(parent, modal);initComponents();
     model.setColumnIdentifiers(new String[]{"Item.", "Descripción" ,"Unid. Medida",
     "Cantidad", "Peso Total"});tablaProductos.setModel(model);
     control.setMaxWidthColumnTable(tablaProductos, 40, 0);
     control.setMaxWidthColumnTable(tablaProductos, 450, 1 );
     control.setMaxWidthColumnTable(tablaProductos, 100, 3, 4);
     
     Component[] components = panelCheck.getComponents();
     for (Component component : components) {
      if (component instanceof JCheckBox) {
       ((JCheckBox) component).addActionListener(this);
      }
     }
     String sede = InfoGeneral.getIdSede();
     if ("3".equals(sede)) {
      chk4.setText("Alquiler");chk7.setText("Préstamo");
      chk8.setText("Traslado de bienes a otro lugar"  );
      chk10.setText("Crédito en letras");
     }
     else {
      chk4.setText("Consignación");chk7.setText("Traslado de bienes para transformación");
      chk8.setText("Recojo de bienes transformados");chk10.setText("Traslado zona primaria");
     }
     cancelar();txtConstanciaInscripcion.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        panelCheck = new javax.swing.JPanel();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        chk6 = new javax.swing.JCheckBox();
        chk7 = new javax.swing.JCheckBox();
        chk8 = new javax.swing.JCheckBox();
        chk9 = new javax.swing.JCheckBox();
        chk10 = new javax.swing.JCheckBox();
        chk11 = new javax.swing.JCheckBox();
        chk12 = new javax.swing.JCheckBox();
        txtOtroMotivo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtDestinatario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRucDestinatario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroLicenciaDeConducir = new javax.swing.JTextField();
        txtMarcaPlacaVehiculo = new javax.swing.JTextField();
        txtNombreTransportista = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRucTransportista = new javax.swing.JTextField();
        txtConstanciaInscripcion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPlacaVehiculo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPuntoDePartida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPuntoDeLlegada = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroGuia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaEmision = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtFechaInicio = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guia de remisión");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaProductos.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(tablaProductos);

        panelCheck.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        chk1.setText("Venta");
        chk1.setName("chk1"); // NOI18N
        chk1.setNextFocusableComponent(chk2);
        chk1.setOpaque(false);

        chk2.setText("Venta sujeto a confirmación del comprador");
        chk2.setName("chk2"); // NOI18N
        chk2.setNextFocusableComponent(chk3);
        chk2.setOpaque(false);

        chk3.setText("Compra");
        chk3.setName("chk3"); // NOI18N
        chk3.setNextFocusableComponent(chk4);
        chk3.setOpaque(false);

        chk4.setText("Alquiler");
        chk4.setName("chk4"); // NOI18N
        chk4.setNextFocusableComponent(chk5);
        chk4.setOpaque(false);

        chk5.setText("Devolución");
        chk5.setName("chk5"); // NOI18N
        chk5.setNextFocusableComponent(chk6);
        chk5.setOpaque(false);

        chk6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chk6.setText("Traslado entre establecimientos de la misma empresa");
        chk6.setName("chk6"); // NOI18N
        chk6.setNextFocusableComponent(chk7);
        chk6.setOpaque(false);

        chk7.setText("Préstamo");
        chk7.setName("chk7"); // NOI18N
        chk7.setNextFocusableComponent(chk8);
        chk7.setOpaque(false);

        chk8.setText("Traslado de bienes a otro lugar");
        chk8.setName("chk8"); // NOI18N
        chk8.setNextFocusableComponent(chk9);
        chk8.setOpaque(false);

        chk9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chk9.setText("Traslado por emisor itinerante de comprobante de pago");
        chk9.setName("chk9"); // NOI18N
        chk9.setNextFocusableComponent(chk10);
        chk9.setOpaque(false);

        chk10.setText("Crédito en letras");
        chk10.setName("chk10"); // NOI18N
        chk10.setNextFocusableComponent(chk11);
        chk10.setOpaque(false);

        chk11.setText("Importación");
        chk11.setName("chk11"); // NOI18N
        chk11.setNextFocusableComponent(chk12);
        chk11.setOpaque(false);

        chk12.setText("Exportación");
        chk12.setName("chk12"); // NOI18N
        chk12.setNextFocusableComponent(txtOtroMotivo);
        chk12.setOpaque(false);

        txtOtroMotivo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("Otro");

        javax.swing.GroupLayout panelCheckLayout = new javax.swing.GroupLayout(panelCheck);
        panelCheck.setLayout(panelCheckLayout);
        panelCheckLayout.setHorizontalGroup(
            panelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCheckLayout.createSequentialGroup()
                        .addGroup(panelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCheckLayout.createSequentialGroup()
                                .addComponent(chk11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chk6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chk1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addGroup(panelCheckLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOtroMotivo)
                        .addContainerGap())))
        );
        panelCheckLayout.setVerticalGroup(
            panelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(chk1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtOtroMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del destinatario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11))); // NOI18N

        txtDestinatario.setEditable(false);
        txtDestinatario.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        txtDestinatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDestinatarioKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 52, 193));
        jLabel11.setText("RUC: ");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 52, 193));
        jLabel8.setText("Razón Social:");

        txtRucDestinatario.setEditable(false);
        txtRucDestinatario.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDestinatario)
                    .addComponent(txtRucDestinatario))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRucDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unidad de transporte / conductor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 52, 193));
        jLabel4.setText("<html>Vehículo Marca :</hmtl>");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 52, 193));
        jLabel6.setText("Vehiculo Placa");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 52, 193));
        jLabel7.setText("N° Lic. De Conducir: ");

        txtNumeroLicenciaDeConducir.setNextFocusableComponent(txtNombreTransportista);
        txtNumeroLicenciaDeConducir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroLicenciaDeConducirKeyPressed(evt);
            }
        });

        txtMarcaPlacaVehiculo.setNextFocusableComponent(txtPlacaVehiculo);
        txtMarcaPlacaVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMarcaPlacaVehiculoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarcaPlacaVehiculoKeyReleased(evt);
            }
        });

        txtNombreTransportista.setNextFocusableComponent(txtRucTransportista);
        txtNombreTransportista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreTransportistaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreTransportistaKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 52, 193));
        jLabel10.setText("RUC:");

        txtRucTransportista.setNextFocusableComponent(chk1);
        txtRucTransportista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRucTransportistaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucTransportistaKeyTyped(evt);
            }
        });

        txtConstanciaInscripcion.setNextFocusableComponent(txtNombreTransportista);
        txtConstanciaInscripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConstanciaInscripcionKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 52, 193));
        jLabel15.setText("Nombre transportista:");

        txtPlacaVehiculo.setNextFocusableComponent(txtNumeroLicenciaDeConducir);
        txtPlacaVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlacaVehiculoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaVehiculoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumeroLicenciaDeConducir, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(txtNombreTransportista)
                    .addComponent(txtRucTransportista)
                    .addComponent(txtConstanciaInscripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlacaVehiculo)
                    .addComponent(txtMarcaPlacaVehiculo))
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarcaPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroLicenciaDeConducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(txtConstanciaInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRucTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 52, 193));
        jLabel2.setText("Punto de Partida: ");

        txtPuntoDePartida.setNextFocusableComponent(txtPuntoDeLlegada);
        txtPuntoDePartida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPuntoDePartidaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPuntoDePartidaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 52, 193));
        jLabel5.setText("Punto de Llegada:");

        txtPuntoDeLlegada.setNextFocusableComponent(txtMarcaPlacaVehiculo);
        txtPuntoDeLlegada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPuntoDeLlegadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPuntoDeLlegadaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPuntoDePartida)
                    .addComponent(txtPuntoDeLlegada))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPuntoDePartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPuntoDeLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 52, 193));
        jLabel1.setText("Número: ");

        txtNumeroGuia.setEditable(false);
        txtNumeroGuia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNumeroGuia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroGuiaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroGuiaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 52, 193));
        jLabel3.setText("Fecha de Inicio del traslado:");

        txtFechaEmision.setDateFormatString("dd/MM/yyyy");
        txtFechaEmision.setNextFocusableComponent(txtFechaInicio);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 52, 193));
        jLabel16.setText("Fecha de Emisión:");

        txtFechaInicio.setDateFormatString("dd/MM/yyyy");
        txtFechaInicio.setNextFocusableComponent(txtPuntoDePartida);

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 52, 193));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardar.setMnemonic('G');
        btnGuardar.setText("Guardar");
        btnGuardar.setPreferredSize(new java.awt.Dimension(110, 33));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 52, 193));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setMnemonic('C');
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(114, 33));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 52, 193));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");
        btnSalir.setPreferredSize(new java.awt.Dimension(90, 33));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 52, 193));
        jLabel9.setText("Factura:");

        txtNumeroFactura.setEditable(false);
        txtNumeroFactura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtNumeroGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(241, 241, 241)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumeroGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txtNumeroLicenciaDeConducirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroLicenciaDeConducirKeyPressed
     control.passFocus(evt, txtConstanciaInscripcion);
    }//GEN-LAST:event_txtNumeroLicenciaDeConducirKeyPressed
    private void txtNumeroGuiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroGuiaKeyPressed
     control.passFocus(evt, txtPuntoDePartida);
    }//GEN-LAST:event_txtNumeroGuiaKeyPressed
    private void txtNumeroGuiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroGuiaKeyReleased
        //        control.mayusculas(txtConductor);
    }//GEN-LAST:event_txtNumeroGuiaKeyReleased
    private void txtPuntoDeLlegadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuntoDeLlegadaKeyPressed
     control.passFocus(evt, txtMarcaPlacaVehiculo);
    }//GEN-LAST:event_txtPuntoDeLlegadaKeyPressed
    private void txtPuntoDeLlegadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuntoDeLlegadaKeyReleased
        //        control.mayusculas(txtPuntoDeLlegada);
    }//GEN-LAST:event_txtPuntoDeLlegadaKeyReleased
    private void txtMarcaPlacaVehiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaPlacaVehiculoKeyPressed
     control.passFocus(evt, txtNumeroLicenciaDeConducir);
    }//GEN-LAST:event_txtMarcaPlacaVehiculoKeyPressed
    private void txtMarcaPlacaVehiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaPlacaVehiculoKeyReleased
        //        control.mayusculas(txtUnidadDeTransporte);
    }//GEN-LAST:event_txtMarcaPlacaVehiculoKeyReleased
    private void txtPuntoDePartidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuntoDePartidaKeyPressed
     control.passFocus(evt, txtPuntoDeLlegada);
    }//GEN-LAST:event_txtPuntoDePartidaKeyPressed
    private void txtPuntoDePartidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuntoDePartidaKeyReleased
     //        control.mayusculas(txtPuntoDePartida);
    }//GEN-LAST:event_txtPuntoDePartidaKeyReleased
    private void txtNombreTransportistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTransportistaKeyPressed
     control.passFocus(evt, txtRucTransportista);
    }//GEN-LAST:event_txtNombreTransportistaKeyPressed
    private void txtNombreTransportistaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTransportistaKeyReleased

    }//GEN-LAST:event_txtNombreTransportistaKeyReleased
    private void txtDestinatarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestinatarioKeyReleased
     //control.mayusculas(txtDestinatario);
    }//GEN-LAST:event_txtDestinatarioKeyReleased
    private void txtRucTransportistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucTransportistaKeyPressed
     control.passFocus(evt, chk1);
    }//GEN-LAST:event_txtRucTransportistaKeyPressed
    private void txtRucTransportistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucTransportistaKeyTyped
     control.Longitudtx(txtRucTransportista, evt, 11);
     control.Solonumeros(evt);
    }//GEN-LAST:event_txtRucTransportistaKeyTyped
    private void txtConstanciaInscripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConstanciaInscripcionKeyPressed
     control.passFocus(evt, txtNombreTransportista);
    }//GEN-LAST:event_txtConstanciaInscripcionKeyPressed
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     if ("Guardar".equals(btnGuardar.getText())) {
      if(ComprobarMmotivo())   
       guardar();
      else
       JOptionPane.showMessageDialog(null,"Debes seleccionar el motivo de traslado");
     } 
     else {
      btnGuardar.setText("Guardar");
      dispose();
     }
    }//GEN-LAST:event_btnGuardarActionPerformed
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
     cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
     idGuiaRemision = null;this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
     idGuiaRemision = null;
    }//GEN-LAST:event_formWindowClosed
    private void txtPlacaVehiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaVehiculoKeyPressed
    private void txtPlacaVehiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaVehiculoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaVehiculoKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGenerarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGenerarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGenerarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGenerarGuiaRemision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmGenerarGuiaRemision dialog = new FrmGenerarGuiaRemision(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk10;
    private javax.swing.JCheckBox chk11;
    private javax.swing.JCheckBox chk12;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JCheckBox chk6;
    private javax.swing.JCheckBox chk7;
    private javax.swing.JCheckBox chk8;
    private javax.swing.JCheckBox chk9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCheck;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtConstanciaInscripcion;
    private javax.swing.JTextField txtDestinatario;
    private com.toedter.calendar.JDateChooser txtFechaEmision;
    private com.toedter.calendar.JDateChooser txtFechaInicio;
    private javax.swing.JTextField txtMarcaPlacaVehiculo;
    private javax.swing.JTextField txtNombreTransportista;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtNumeroGuia;
    private javax.swing.JTextField txtNumeroLicenciaDeConducir;
    private javax.swing.JTextField txtOtroMotivo;
    private javax.swing.JTextField txtPlacaVehiculo;
    private javax.swing.JTextField txtPuntoDeLlegada;
    private javax.swing.JTextField txtPuntoDePartida;
    private javax.swing.JTextField txtRucDestinatario;
    private javax.swing.JTextField txtRucTransportista;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     JCheckBox chk = (JCheckBox) e.getSource();
     if (chk.isSelected()) {
      motivoTraslado += chk.getName().replace("chk", "") + ",";
     }
     else {
      motivoTraslado = motivoTraslado.replace(chk.getName().replace("chk", "") + ",", "");
     }
    }
    private void generarNumeroGuia() {
     control.Sql = "call ElComprobante('0','" + Controlador.sede + "','Guia de Remision','Productos','0','1')";
     if (control.DevolverRegistroDto(control.Sql, 1).equals("Se debe iniciar este tipo de comprobante")) {
      JOptionPane.showMessageDialog(this, "No hay documentos de ese tipo, por favor primer incie la numeración del documento", "Mensaje", JOptionPane.WARNING_MESSAGE);
      this.dispose();
     }
     else {
      txtNumeroGuia.setText(control.DevolverRegistroDto(control.Sql, 1));
      idComprobanteGenerado = control.DevolverRegistroDto(control.Sql, 3);
     }
    }
    private void cancelar() {
     txtNumeroGuia.setText("");generarNumeroGuia();
     txtFechaEmision.setDate(new Date());txtFechaInicio.setDate(new Date());
     txtPuntoDePartida.setText("");txtPuntoDeLlegada.setText("");
     txtMarcaPlacaVehiculo.setText("");txtNumeroLicenciaDeConducir.setText("");
     txtConstanciaInscripcion.setText("");txtNombreTransportista.setText("");
     txtRucTransportista.setText("");txtOtroMotivo.setText("");
     motivoTraslado = "";Component[] components = panelCheck.getComponents();
     for (Component component : components) {
      if (component instanceof JCheckBox) {
       ((JCheckBox) component).setSelected(false);
      }
     }
     generarNumeroGuia();control.LimTabla(model);setIdVenta(idVenta);
    }
    public void setIdVenta(String idVenta) {
     this.idVenta = idVenta;
     String sql = String.format("SELECT c.`serie`, c.`nume`, cl.`nomclie`, i.`numident` "
     + "FROM comprobantes c, compventa cv, cliente cl, identificacion i, venta v "
     + "WHERE c.`idComprobantes`=cv.`idComprobantes` "+ "AND cv.`idVenta`=%s AND "
     + "i.`idCliente`=cl.`idCliente` "+ "AND v.`idVenta`=cv.`idVenta` AND v.`idCliente`"
     + "=cl.`idCliente`;", idVenta);String[] arrayData = control.getArrayData(sql);
     if (arrayData != null) {
      txtNumeroFactura.setText(arrayData[1]);txtDestinatario.setText(arrayData[2]);
      txtRucDestinatario.setText(arrayData[3]);
     }
     
     /*sql = String.format("SELECT d.`cant`, u.`abre`,c.`nomctlg` FROM catalogoproducto "
     + "c, detventafacturar d, unidad u WHERE c.`codctlg`=d.`codctlg` "+ "AND c."
     + "`idUnidad`=u.`idUnidad` AND d.`idVenta`=%s;", idVenta);
     */
     control.Sql="select @itm:=@itm+1 Item,concat(md.nommod,' ',mr.nommrc,' ',cp.nomctlg) "
     + "Descripcion,u.nomuni Unidad,dvf.cant Cantidad from (select @itm:=0) I,venta v inner "
     + "join detventafacturar dvf on v.idventa=dvf.idventa inner join catalogoproducto cp " +
     "on cp.codctlg=dvf.codctlg inner join unidad u on u.idunidad=cp.idunidad inner join "
     + "modelocatalogo mc on mc.codctlg=cp.codctlg inner join modelo md on md.idmodelos="
     + "mc.idmodelos inner join marca mr on cp.idmarca=mr.idmarca where v.idventa='"+idVenta+"'";
     
     ResultSet resultProductos = control.DevolverRegistro(control.Sql);
     try {
      while (resultProductos.next()) {
       String row[] = new String[5];row[0] = resultProductos.getString(1);
       row[1] = resultProductos.getString(2);row[2] = resultProductos.getString(3);
       row[3] = resultProductos.getString(4);row[4] = "";model.addRow(row);
      }
     }
     catch (SQLException ex) {
      Logger.getLogger(FrmGenerarGuiaRemision.class.getName()).log(Level.SEVERE, null, ex);
     }
    }
    private void guardar() {
     if(txtRucTransportista.getText().trim().length()==0){
      JOptionPane.showMessageDialog(null,"Falta el ruc del trasportista");
      txtRucTransportista.grabFocus();return;
     }
     else{
      if(txtRucTransportista.getText().trim().length()<11){
       JOptionPane.showMessageDialog(null,"El ruc debe tener 11 digitos");
       txtRucTransportista.grabFocus();return;   
      }   
     }    
     String fechaEmision = control.Formato_Amd(txtFechaEmision.getDate());
     String fechaInicio = control.Formato_Amd(txtFechaInicio.getDate());
     String puntoDePartida = txtPuntoDePartida.getText().trim();
     String puntoDeLLegada = txtPuntoDeLlegada.getText().trim();
     String marcaPlacaVehiculo = txtMarcaPlacaVehiculo.getText().trim();
     String numeroLicenciaConducir = txtNumeroLicenciaDeConducir.getText().trim();
     String constanciaInscripcion = txtConstanciaInscripcion.getText().trim();
     String nombreTransportista = txtNombreTransportista.getText().trim();
     String rucTransportista = txtRucTransportista.getText().trim();
     String placavehi = txtPlacaVehiculo.getText().trim();generarNumeroGuia();
     String sql = "INSERT INTO guiaremision VALUES(NULL,%s,%s,'%s','%s','%s','%s',"
     + "'%s','%s','%s','%s','%s','%s','%s');";
     control.Sql = String.format(sql, idComprobanteGenerado, idVenta, fechaEmision, 
     fechaInicio, puntoDePartida, puntoDeLLegada,marcaPlacaVehiculo, numeroLicenciaConducir,
     constanciaInscripcion, nombreTransportista, rucTransportista, motivoTraslado + 
     " Otro: " + txtOtroMotivo.getText(),placavehi);
     
     idGuiaRemision = "" + control.executeAndGetId(control.Sql);
     control.EditarRegistro("UPDATE comprobantes c SET c.`esta`='Emitido' WHERE c.`"
     + "idComprobantes`='" + idComprobanteGenerado + "';");
     if (idGuiaRemision != null) {
      JOptionPane.showMessageDialog(this, "La guía de remisión se ha generado "
      + "correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
      Map map = new HashMap();map.put("idGuia", String.valueOf(idGuiaRemision));
      map.put("codv", System.getProperties().getProperty("user.dir")+"\\src\\Reportes\\");
      String sede = InfoGeneral.getIdSede();
      
      if ("3".equals(sede)) 
       control.showReportDialog("Guía de Remisión", "guiaDeRemisionInfotel", map);
      
      else 
       control.showReportDialog("Guía de Remisión", "guiaDeRemisionICE", map);
      
      dispose();
     }
     else {
      JOptionPane.showInternalMessageDialog(this, "Ocurrió un error al procesar el registro", 
      "Mensaje", JOptionPane.WARNING_MESSAGE);
     }
    }
    public String getIdGuiaRemision() {
        return idGuiaRemision;
    }
    public boolean ComprobarMmotivo(){
     boolean bd=false;
     if(chk1.isSelected())
      bd=true;        
     else{
      if(chk2.isSelected())
       bd=true;         
      else{   
       if(chk3.isSelected())
        bd=true;          
       else{   
        if(chk4.isSelected())
         bd=true;           
        else{
         if(chk5.isSelected())
          bd=true;            
         else{   
          if(chk6.isSelected())
           bd=true;             
          else{   
           if(chk7.isSelected())
            bd=true;              
           else{   
            if(chk8.isSelected())
             bd=true;               
            else{   
             if(chk9.isSelected())
              bd=true;                
             else{   
              if(chk10.isSelected())
               bd=true;                 
              else{   
               if(chk11.isSelected())
                bd=true;                  
               else{    
                if(txtOtroMotivo.getText().trim().length()>0)
                 bd=true;      
               }
              }
             }
            }
           }
          }
         }
        }           
       }     
      }
     }         
     return bd;
    }
}
