/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Miguel Silva
 */
import Clases.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Rep_Distribuidos extends javax.swing.JInternalFrame {
    Controlador control=new Controlador();Mimodelo modelo=new Mimodelo();
    public Rep_Distribuidos() {
      initComponents();tProductos.setModel(modelo);setTitle("                                       Reporte de  Distribución de Productos");
      modelo.setColumnIdentifiers(new String[] {"Código","Producto","Marca","Serie","P.Venta","Costo"});
     this.setFrameIcon(new ImageIcon(this.getClass().getResource("/Imagenes/icoChiqui.png")));
      tProductos.getColumnModel().getColumn(1).setPreferredWidth(350);
      tProductos.getColumnModel().getColumn(2).setPreferredWidth(150);      
      tProductos.getColumnModel().getColumn(3).setPreferredWidth(200);      
      control.LlenarCombo(cboUbicacion,"Select * from sede",2);
     cboSituacion.setSelectedIndex(0);
     jButton3.setVisible(false);
     //control.forma_table_ver(modelo, tProductos); 
     FormatoTabla ft = new FormatoTabla(1);
     tProductos.setDefaultRenderer(Object.class, ft);
     
     tProductos.getColumnModel().getColumn(0).setPreferredWidth(150);
     
      cboUbicacion.addActionListener(new ActionListener() {

          @Override
          public void actionPerformed(ActionEvent e) {
            MostrarProductos();
          }
      });
      cboSituacion.addActionListener(new ActionListener() {

          @Override
          public void actionPerformed(ActionEvent e) {
       //       throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
              MostrarProductos();
          }
      });
    }
    
    
    public void Cancelar(){
     cboSituacion.setSelectedIndex(-1);cboUbicacion.setSelectedIndex(-1);
     control.LimTabla(modelo);cboUbicacion.grabFocus();
    }
    public void MostrarProductos(){
     if((cboSituacion.getSelectedIndex()>=0)&&(cboUbicacion.getSelectedIndex()>=0)){
      control.Sql="SELECT Codigo,Producto,Marca,Serie,P_venta,Costo FROM vta_maestra_producto where sede='"+cboUbicacion.getSelectedItem().toString()+"'"
     + " and estado='"+cboSituacion.getSelectedItem().toString()+"'";   
      control.LlenarJTablaSE(modelo,control.Sql,6);    
     }   
     else{
      JOptionPane.showMessageDialog(rootPane, "Debe seleccionar los dos criterios de busqueda");
      control.Sql="SELECT * FROM vta_maestra_producto where sede='nada'"
     + " and estado='"+cboSituacion.getSelectedItem().toString()+"'";   
      control.LlenarJTablaSE(modelo,control.Sql,6);       
     }
     
    }
    public void Imprimir(){
     if(tProductos.getRowCount()>0){
      control.impresor.ImpresionesDistribucion("Distribucion de productos","ProductosxSede", "Sede",
      cboUbicacion.getSelectedItem().toString(),"Estado",cboSituacion.getSelectedItem().toString());
      
     }  
     else{
      JOptionPane.showMessageDialog(rootPane,"No hay nada para imprimir");
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboUbicacion = new javax.swing.JComboBox();
        cboSituacion = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de selección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Situación");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Ubicación");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jPanel1.add(cboUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 210, -1));

        cboSituacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disponible", "Vendido" }));
        cboSituacion.setSelectedIndex(-1);
        jPanel1.add(cboSituacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 210, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setMnemonic('v');
        jButton3.setText("Ver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tProductos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 850, 330));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 870, 380));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print.png"))); // NOI18N
        jButton1.setMnemonic('m');
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 123, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButton2.setMnemonic('s');
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 121, 40));

        Cancelar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(0, 0, 102));
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        Cancelar.setMnemonic('c');
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel3.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 130, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 870, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Imprimir();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     MostrarProductos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
     //MostrarProductos();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
     Cancelar();
    }//GEN-LAST:event_CancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox cboSituacion;
    private javax.swing.JComboBox cboUbicacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tProductos;
    // End of variables declaration//GEN-END:variables
}
