/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
/********* @author User *****/
import Clases.*;import com.toedter.calendar.JDateChooser;
import java.beans.PropertyChangeEvent;import java.lang.reflect.Field;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class RepPagosxDeudas extends javax.swing.JInternalFrame {

    //******************************ATRIBUTOS***********************************
    Controlador control=new Controlador();Mimodelo modelo=new Mimodelo();
    //******************************ATRIBUTOS***********************************
    
    //******************************METODOS*************************************
    public RepPagosxDeudas() {
     initComponents();TPagosDeuda.setModel(modelo);this.setFrameIcon(new ImageIcon(this.getClass().getResource("/Imagenes/icoChiqui.png")));
     modelo.setColumnIdentifiers(new String[] {"ID","Cliente","Fec_Pago","Mto_Pagado",
     "Forma de pago"});f_Desde.setDate(new Date());F_Hasta.setDate(new Date());
     control.setWidthTableColumn(TPagosDeuda,250,1,4);
     Mostrar();
     //****************************CONTROLAR EL CAMBIO DE FECHA***********************************
     f_Desde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      @Override
      public void propertyChange(PropertyChangeEvent evt) {
       if("date".equals(evt.getPropertyName())){
        JDateChooser isse=(JDateChooser)evt.getSource();
        boolean isdatasele=false;
        try {
         Field dateselfi=JDateChooser.class.getDeclaredField("dateSelect");
         dateselfi.setAccessible(true);
         isdatasele=dateselfi.getBoolean(isse);
        } 
        catch (Exception e) {
         Mostrar();
        }
       }
      }
     });
     F_Hasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      @Override
      public void propertyChange(PropertyChangeEvent evt) {
       if("date".equals(evt.getPropertyName())){
        JDateChooser isse=(JDateChooser)evt.getSource();
        boolean isdatasele=false;
        try {
         Field dateselfi=JDateChooser.class.getDeclaredField("dateSelect");
         dateselfi.setAccessible(true);
         isdatasele=dateselfi.getBoolean(isse);
        } 
        catch (Exception e) {
         Mostrar();
        }
       }
      }
     });
     //****************************CONTROLAR EL CAMBIO DE FECHA***********************************
    }
    public void Mostrar(){
     control.Sql="select concat(i.desident,' ',i.numident) as ID,c.nomclie Cliente,"
     + "DATE_FORMAT(pd.fecpgxdeu,'%d/%m/%Y') F_Pago,pd.montpag MontoPagado,if(pd.montpag>0,pd.detalle,"
     + "'No pago nada al inicio') Forma,c.idcliente from venta v,compventa cv,"
     + "comprobantes cb,tipocomprobante tc,cliente c,pagoxdeuda pd,deuda d,identificacion i"
     + " where v.idcliente=c.idcliente and c.idcliente=i.idcliente and v.idventa=cv.idventa"
     + " and cv.idcomprobantes=cb.idcomprobantes and tc.idTipoComprobante=cb.idTipoComprobante"
     + " and d.idventa=v.idventa and d.iddeuda=pd.iddeuda and pd.montpag>0 and (c.nomclie like'%"+
     txtBuscar.getText()+"%' or i.numident like'%"+txtBuscar.getText()+"%') and "
     + "pd.fecpgxdeu between '"+control.Formato_Amd(f_Desde.getDate())+"' and '"+
     control.Formato_Amd(F_Hasta.getDate())+"'";control.LlenarJTabla(modelo,control.Sql,5);     
     
     
    }
    public void Cancelar(){
         
    }
    public void Imprimir(){
     if(TPagosDeuda.getRowCount()>0){
      control.impresor.Imprimircon5Parametros("Pagos Por Deudas","RepPagosxDeuda",
      "bsc","fde","fha","fdemst", "dhamst",txtBuscar.getText(),control.Formato_Amd(
      f_Desde.getDate()),control.Formato_Amd(F_Hasta.getDate()),control.Formato_DMA(
      f_Desde.getDate()),control.Formato_DMA(F_Hasta.getDate()));
     }   
     else{
         JOptionPane.showMessageDialog(rootPane,"Nada para imprimir");
     }
         
    }
    //******************************METODOS*************************************
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPagosDeuda = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        f_Desde = new com.toedter.calendar.JDateChooser();
        F_Hasta = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bImprimir = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Pagos por Deuda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TPagosDeuda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TPagosDeuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPagosDeudaMouseClicked(evt);
            }
        });
        TPagosDeuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TPagosDeudaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TPagosDeuda);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1050, 360));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Buscar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, -1, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 25, 280, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Hasta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Desde");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        f_Desde.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(f_Desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 25, 130, -1));

        F_Hasta.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(F_Hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 420));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCancelar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        bCancelar.setMnemonic('a');
        bCancelar.setText("Cancelar");
        bCancelar.setMargin(new java.awt.Insets(2, 1, 2, 14));
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(bCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 13, 110, 40));

        bSalir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        bSalir.setMnemonic('s');
        bSalir.setText("Salir");
        bSalir.setMargin(new java.awt.Insets(2, 1, 2, 14));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel2.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 13, 110, 40));

        bImprimir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Print.png"))); // NOI18N
        bImprimir.setMnemonic('i');
        bImprimir.setText("Imprimir");
        bImprimir.setMargin(new java.awt.Insets(2, 1, 2, 14));
        bImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(bImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 390, 65));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TPagosDeudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPagosDeudaMouseClicked
     //        CargarDatosMovimiento();
    }//GEN-LAST:event_TPagosDeudaMouseClicked
    private void TPagosDeudaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TPagosDeudaKeyReleased
        //        CargarDatosMovimiento();
    }//GEN-LAST:event_TPagosDeudaKeyReleased
    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
     Mostrar();
    }//GEN-LAST:event_txtBuscarKeyReleased
    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        //CalcularMontodeCaja();
    }//GEN-LAST:event_jPanel1MouseMoved
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        Cancelar();
    }//GEN-LAST:event_bCancelarActionPerformed
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bSalirActionPerformed
    private void bImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImprimirActionPerformed
     Imprimir();
    }//GEN-LAST:event_bImprimirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser F_Hasta;
    private javax.swing.JTable TPagosDeuda;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bImprimir;
    private javax.swing.JButton bSalir;
    private com.toedter.calendar.JDateChooser f_Desde;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
